name: Build, Push

on:
  push:
    branches:
      - code-server-home-assistant
    paths-ignore:
      - '**/README.md'
  schedule:
    - cron: '43 20 */7 * *'

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: code-server-home-assistant

jobs:  
  build_assess_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Attempt Build
        run: docker build . --file Dockerfile -t $IMAGE_NAME
        
      - name: Log into Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Image
        run: |
          IMAGE_ID=ghcr.io/aneisch/${{ env.IMAGE_NAME }}
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=latest
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
